# Config
# Author: Yuanjie Yue
# Date: 10/16/2019

WEB_API_SERVER = 'localhost'
WEB_API_PORT = 8180
EXPRESSION_EVAL_SERVER = 'localhost'
EXPRESSION_EVAL_PORT = 8181
CACHE_SERVER = 'localhost'
CACHE_PORT = 8182